version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-
      - run:
          name: Clone Arc dependency at required commit
          command: |
            git clone https://github.com/Anuken/Arc.git ../Arc
            cd ../Arc && git checkout 8c17f18ffb
      - run:
          name: Run unit tests
          command: ./gradlew tests:test --rerun --stacktrace --no-daemon -PlocalArc=true
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - store_test_results:
          path: tests/build/reports/tests/test

workflows:
  build-and-test:
    jobs:
      - test
